# Experimental!
Hex ← ⌅(÷255⋕₁₆↯3_2|♭≡(⬚⌞@0↯¤2°□)°⋕₁₆⁅×255)

┌─╴Colors
  ┌─╴Bases
    White  ← Hex"e0f4ec"
    Red    ← Hex"ac5546"
    Orange ← Hex"b7824b"
    Yellow ← Hex"b3a543"
    Green  ← Hex"4ea456"
    Teal   ← Hex"22a59c"
    Blue   ← Hex"3c7ab5"
    Purple ← Hex"806bb2"
    Pink   ← Hex"9f4a91"
    Accent ← Hex"9c435a"
  └─╴

  Grayscale ← ≡⌟×0.0826_0.105_0.1415_0.175_0.215_0.285_0.43_0.572_0.715_0.855_1 Bases.White
  Reds      ← ≡⌟×0.86_1_1.13 Bases.Red
  Oranges   ← ≡⌟×0.86_1_1.13 Bases.Orange
  Yellows   ← ≡⌟×0.86_1_1.13 Bases.Yellow
  Greens    ← ≡⌟×0.86_1_1.13 Bases.Green
  Teals     ← ≡⌟×0.86_1_1.13 Bases.Teal
  Blues     ← ≡⌟×0.86_1_1.13 Bases.Blue
  Purples   ← ≡⌟×0.86_1_1.13 Bases.Purple
  Pinks     ← ≡⌟×0.86_1_1.13 Bases.Pink
  Accents   ← ≡⌟×0.86_1_1.13 Bases.Accent
└─╴

Colors!(
  Grayscale
  ⊃(&s$GHexes≡°Hex|/≡⊂≡(↯30_30_3))
  Reds_Oranges_Yellows_Greens_Teals_Blues_Purples_Pinks_Accents
  ⊃(&s$Hexes≡₁°Hex|/⊂≡/≡⊂≡₁(↯30_30_3))
)
&ims ˜⊂≡▽˜◡(÷∩⧻₁) ⇌⤸1
